service: tripservice
frameworkVersion: '3'

plugins:
  - serverless-middleware
  - serverless-offline

custom:
  middleware:
    pre:
      - check.authorize

provider:
  name: aws
  runtime: nodejs18.x
  


functions:
  createTrip:
    handler: trip/tripContrller.createTrip
    events:
      - httpApi:
          path: /createTrip
          method: POST    
    middleware:
      pre:
        - check.authorize 
  
  editTrip:
    handler: trip/tripContrller.editTrip
    events:
      - httpApi:
          path: /editTrip
          method: POST

  getAlltrip:
    handler: trip/tripContrller.getAlltrip
    events:
      - httpApi:
          path: /getAlltrip
          method: get

  addExpenses:
    handler: trip/tripContrller.addExpenses
    events:
      - httpApi:
          path: /addExpenses
          method: POST

  gettripExpensesBycatogry:
    handler: trip/tripContrller.gettripExpensesBycatogry
    events:
      - httpApi:
          path: /gettripExpensesBycatogry
          method: POST
  
