service: Profile
frameworkVersion: '3'

plugins:
  - serverless-dotenv-plugin
  - serverless-offline

provider:
  name: aws
  runtime: nodejs18.x
  memorySize: 128


functions:
  registerapi:
    handler: profile/profileControler/registerUse
    events:
      - httpApi:
          path: /register
          method: POST
